from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import json
import os
import uvicorn
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="BrainOS Multi-Agent Backend")

# We use an OpenAI compatible client. 
# For local testing, it defaults to OpenAI API if OPENAI_API_KEY is present.
# When moving to MI300X, we will change base_url to the vLLM endpoint.
vllm_url = os.getenv("VLLM_API_BASE")
client = OpenAI(
    base_url=vllm_url if vllm_url else None,
    api_key=os.getenv("OPENAI_API_KEY", "") # Need dummy key if using vLLM without auth
)

# Dummy Agent classes for structure
class IngestionAgent:
    def process_sources(self, filepath: str):
        with open(filepath, "r") as f:
            data = json.load(f)
        return {"status": "success", "processed_count": len(data), "items": data}

class StructuringAgent:
    def embed_and_store(self, items: List[dict]):
        # Mock embedding step
        return {"status": "success", "graph_nodes_updated": len(items)}

class ExecutionAgent:
    def execute(self, query: str):
        # In a real scenario, this retrieves from vector DB, then asks the LLM
        if not os.getenv("OPENAI_API_KEY") and not vllm_url:
            return "Local LLM not configured. Please set OPENAI_API_KEY or VLLM_API_BASE."
        
        try:
            response = client.chat.completions.create(
                model=os.getenv("MODEL_NAME", "gpt-4o-mini"),
                messages=[
                    {"role": "system", "content": "You are the BrainOS execution agent. You answer questions based on company knowledge."},
                    {"role": "user", "content": query}
                ],
                max_tokens=150
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Error executing query via LLM: {str(e)}"

class FeedbackAgent:
    def evaluate(self, answer: str):
        # Mock evaluation step
        return {"confidence": 0.95, "feedback": "Answer seems well grounded in knowledge base."}

# Initialize Agents
ingest_agent = IngestionAgent()
struct_agent = StructuringAgent()
exec_agent = ExecutionAgent()
feedback_agent = FeedbackAgent()

class QueryRequest(BaseModel):
    query: str

@app.get("/health")
def health_check():
    return {"status": "ok", "gpu_backend": "vLLM" if vllm_url else "OpenAI fallback"}

class IngestRequest(BaseModel):
    kind: str
    title: str
    content: str
    url: Optional[str] = None

@app.post("/api/ingest_mock")
def ingest_mock_data():
    """Trigger the ingestion of the mock data generated by seed_demo_data.py"""
    data_file = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data", "mock_sources.json")
    if not os.path.exists(data_file):
        raise HTTPException(status_code=404, detail="Mock data not found. Run seed_demo_data.py first.")
    
    ingest_result = ingest_agent.process_sources(data_file)
    struct_result = struct_agent.embed_and_store(ingest_result["items"])
    
    return {
        "message": "Mock data ingested and structured.",
        "ingestion": ingest_result,
        "structuring": struct_result
    }

@app.post("/api/ingest")
def ingest_live_data(req: IngestRequest):
    """Trigger the ingestion of live data sent from the Next.js UI."""
    # Mock processing of a single item
    item = {
        "id": "live-" + str(hash(req.content)),
        "source_type": req.kind,
        "author": "System",
        "content": req.content,
        "title": req.title
    }
    struct_result = struct_agent.embed_and_store([item])
    
    return {
        "message": "Live data ingested and structured.",
        "structuring": struct_result
    }

@app.post("/api/ask")
def ask_brainos(req: QueryRequest):
    """The main entry point for the Next.js UI to ask questions."""
    answer = exec_agent.execute(req.query)
    feedback = feedback_agent.evaluate(answer)
    
    return {
        "query": req.query,
        "answer": answer,
        "feedback": feedback
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8081)
